# Generated by Django 3.0.5 on 2023-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20230521_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprescriptiondata',
            name='treatment_received_on',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprescriptiondata',
            name='patientIDKey',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
